# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "IITG MUN"
email: "iitgmun@alcheringa.in"
description: "IIT Guwahati MUN Spring'18"
baseurl: "/"
url: http://iitgmun.org/
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "iitgmun.org"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "IITG MUN"
organizerAlternateName: "IIT Guwahati MUN"
organizerDescription: "IIT Guwahati MUN Spring'18"
organizerEmail: "iitgmun@alcheringa.in"
organizerLogo: "/img/favicons/favicon.png"
organizerLink: "iitgmun.org"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/favicons/favicon.png"
socialImageSrcTwitter: "/img/favicons/favicon.png"
socialImageSrcFacebook: "/img/favicons/favicon.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
# speakers = contact us
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/team/", text: "About Us"}
 - {permalink: "/contact-us/", text: "Contact Us"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Apply now"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Apply now"}
applyLink:
 - {permalink: "/apply", text: "Apply"}

# CHANGE , TODO
apply-link: "/apply/"

# Councils link
lok-sabha-link: "/lok-sabha/"
ecosoc-link: "/ecosoc/"
unga-link: "/unga/"

# Hero Block
heroImage: "hero.jpg"
heroTitle: "IIT GUWAHATI MUN <typeout>"
eventDate: "2-4 February 2018"
typeoutFallback: ""
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Apply now"}

# About Block
aboutTitle: "LETTER FROM THE SECRETARY GENERAL"
letterContent: "Dear Delegates,\n

As the Secretary General of IIT Guwahati Model United Nations Conference (IITGMUN) 2018, I could not be more venerated to welcome you all on behalf of my passionate team to the most ambitious version of the IIT Guwahati Model United Nations Conference - Alcheringa yet.

Every year, IITGMUN endeavors to provide a simulated learning platform to like-minded folks with a zealous passion for debating, international diplomacy as well as politics, and deliberative problem-solving. As a learning conference, we prioritize the development of mindset for finding the solutions to pressing world issues by putting oneself in the shoes of a country's representative. We believe that the best way to learn about international diplomacy is by actually doing it. At its core, the IITGMUN Conference is planned, organized, and directed in its totality by a passionate team of IIT Guwahati students that hail from different academic and cultural backgrounds, bringing their unique experiences to the dais. Over the years, we have been successful in delivering thought-intensive conferences to novice as well as seasoned delegates.  

The contemporary world scenario has been dominated by disruptions, both positive and negative. While the former can serve as a driving force for the global growth engine, dealing with the latter requires meticulous planning and deliberation. As a proponent of this thought, we have handpicked three agendae for this winter and set the floor for discussion on the same.

Namely:
UNGA: Preparing for Trans-Arctic Seafaring: Resolving the Impasse over the North-West Passage

ECOSOC: Fulfilling UN Sustainable Development Goals in the Age of Artificial Intelligence

Lok Sabha : Elucidation of Privacy and its Consequences as a Right

All these agendae are the product of incessant discussions and brainstorming among the team members to deliver the most debatable and relevant global quandaries to the participants. The selectivity of these agendae itself reflects our commitment to deliver the best we possibly can and traverse beyond the conventional line of thought.
  
We as a generation have the best time and resources, enumerated with the experience of older generations, to shape the world in a way we want. The onus is on us to act and deliberate as the choices of today will be governing the future in an unprecedented manner.

With an abyssal optimism, I leave you with the mantle and ask you to take part in an event that awaits a brilliant ensemble of delegates who dare to take on upcoming challenges in the world with courage and diplomacy. Wishing you all the very best of luck for the conference.

Sincerely,
Paridhi Kothari
Secretary General
IIT Guwahati Model UN Conference
"
letterImage: "conference.jpg"
aboutBlock:
 - {title: "", image: "conference.jpg", text: "Dear participants, Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "450", specialCharacter: "+", info: "Delegates", detail: "from all over India"}
 - {count: "25", specialCharacter: "+", info: "Executive Board", detail: "overall"}
 - {count: "20", specialCharacter: "+", info: "International Press", detail: "from country and beyond"}

# Latest News Block
latestNewsTitle: "COUNCILS"
latestNewsBlock:
 - {title: "Lok Sabha", image: "unsc_logo.jpg", text: "", link: "lok-sabha"}
 - {title: "UNGA", image: "unga_logo.jpg", text: "", link: "unga"}
 - {title: "ECOSOC", image: "ecosoc_logo.jpg", text: "", link: "ecosoc"}

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Executive Board"
rockstarSpeakersButtonText: "See all members"

# Reviews Block
reviewsTitle: "Reviews"
review3: "Yes, the IITG MUN has amazing discussions, but the best part of this MUN has to be the people. We are united by the strongest bond of common interests. Continuous open dialogue with people we only know by country names during the conference and the supportive MUN community is, by far, its most beautiful part."
review3Author: "Ariktha Srivathsan"
reviewsImage: "reviews.jpg"
reviewsBackgroundImage: "reviewsBG.jpg"
review1: "It's a really amazing platform to learn not only about the affairs of the world but also about how to articulate your thoughts and put them into words."
review1Author: "Vishwaprasanna Hariharan"
review2: "A Great platform to gain knowledge about the way things are being operated in the real world and to discuss its pros and cons"
review2Author: "Sudhanshu Bhatia"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Indian Institute of Technology,"
venueFeature1: "Guwahati"
venueFeature2: "Conference Hall"

# Tweets Feed Block
tweetsFeedTitle: "Prizes worth 1.5 lakh INR"
twitterHashTag: "IITGMUN18"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"


# Footer
socialLinks:
 - {link: "https://plus.google.com/107674802951013132554", icon: "google-plus"}
 - {link: "https://twitter.com/iitg_mun", icon: "twitter"}
 - {link: "https://www.facebook.com/iitgmun/", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://iitgmun.wordpress.com", text: "Blog"}

# Team Block
teamBlockTitle: "About us"
aboutUs: "The MUN, or the Model United Nations, is a simulation of the actual UN. The participants pretend to represent a nation, and come to together to discuss the very same issues being debated upon in the UN. This gives a normal person the opportunity to know what’s its like to stand for something more than himself/herself, and to experience the complicated the verbal dance and that politicians and delegates take part in everyday. The MUN is a conclave for ideation by the fresh minds of our nation, to brainstorm solutions to problems plaguing our world. Participants work through the tenuous relationships between nations as they deliberate towards a resolution – and they get to look
nice in a suit and tie while they do it!"

# Contact Us block
contactUsBlockTitle: "Contact Us"
contactUsTopImage: "top-section.jpg"
contacts:
 - {name: "Sujal Harsh Ranjan", designation: "USG Infra", contactNumber: "+91 8486772158", fbLink: "https://www.facebook.com/Suji131211"}
 - {name: "Sangam Sharma", designation: "USG Delegate Affairs", contactNumber: "+91 8486808779", fbLink: "https://www.facebook.com/sangam.sharma.90226628"}
 - {name: "Vijayant Balhara", designation: "USG Social and Economic Affairs", contactNumber: "+91 9811040041", fbLink: "https://www.facebook.com/vijayant.balhara.3"}
locationImage: "location.jpg"

#Sponsors block
sponsorsTitle: "In Association with "
sponsorsList:
 - {title: "mun_planet", image: "mun_planet_logo.png"}
 - {title: "mun_turkey", image: "mun_turkey_logo.png"}

sponsors2Title: "In Collaboration with "
sponsors2List:
 - {title: "techfest_world_mun", image: "techfest_world_mun_logo.png"}
 - {title: "patna_mun", image: "patna_mun_logo.png"}


# Apply Block
applyTypes:
 - {type: "Delegate", applyLink: "https://goo.gl/xMbHnu", image: "Delegate.png"}
 - {type: "Executive Board", applyLink: "https://goo.gl/forms/SiCEGaZICk0CbR9H3", image: "EB app.png"}
 - {type: "International Press", applyLink: "https://goo.gl/86F8Mh", image: "Press app.png"}

# Committee Block
applyTypes2:
 - {type: "UNGA", applyLink: "https://docs.google.com/forms/d/e/1FAIpQLSddOHJTjWXhNVdLAB0swRswJlDYSDcuigaz6qFri_9d9sKVsQ/viewform?usp=sf_link", imagery: "UNGA.png"}
 - {type: "LOK SABHA", applyLink: "https://docs.google.com/forms/d/1hR2Ul7I0VlTav_Xdjv4D_f7fUA705EXAzdg6GW168I8/viewform", imagery: "Lok Sabha.png"}
 - {type: "ECOSOC", applyLink: "https://docs.google.com/forms/d/e/1FAIpQLScCs2IwujVf50S1NRUsaF0ZbUsFKCsRlKQ-8DS4NCE_osPMxQ/viewform", imagery: "ECOSOC.png"}

# Apply Block WTO
applyTypes3:
 - {type: "Delegate", applyLink: "https://goo.gl/xMbHnu", image: "Delegate.png"}
 - {type: "Executive Board", applyLink: "https://goo.gl/forms/m1wdPYnQJ7QEsgbl2", image: "EB app.png"}
 - {type: "International Press", applyLink: "https://goo.gl/forms/whankT1dRGjfoO0I3", image: "Press app.png"}


lok-sabha-title: "Lok Sabha"
lok-sabha-agenda-text: "Amendement to the Transgender Rights Bill: Empowerment, Anti-Discrimination, and Gender Dysphoria"
about-lok-sabha-text: "Lok Sabha is composed of representatives of the people chosen by direct election on the basis of the adult suffrage..."
lok-sabha-popup-text-about: "The Lok Sabha, which literally translates to ‘House of the People’ is the lower house of India's bicameral Parliament, the upper house being the Rajya Sabha. It has the power to pass bills on legislative, financial, executive, constitutional, electoral as well as judicial matters.’The Rules of Procedure and Conduct of Business in Lok Sabha’, as well as occasional ‘Directions issued by the Speaker’ regulate the procedure in Lok Sabha."
lok-sabha-popup-text-agenda: "Transgenders have lived through most of modern history as social pariahs. Until recently, there had been little systemic accomodation of this community. This changed with supreme court's historic judgement to recognise them as people of a third gender. A certain “Transgender Rights Bill” was proposed in the Rajya Sabha, which was passed after much political dialogue and discussion. However, upon being tabled in the Lok Sabha, it was amended as “The Transgender Persons Bill” to a virtually unrecognizable extent. Hence, this winter session the Lok Sabha shall convene to argue issues of much humanitarian consequence like the right to self identification of gender, medical tests for gender determination, reservation for transgenders, hate speech as a criminal offence and a plethora of other intricate issues."
lokSabhaTopImage: "lok-sabha-top.jpg"

unga-title: "United Nations General Assembly"
unga-agenda-text: "Safeguarding Privacy in the Era of Mass Surveillance"
about-unga-text: "The General Assembly (GA) is the main deliberative, policymaking and representative organ of the UN. Decisions on important questions, such as..."
unga-popup-text-about: "The General Assembly (GA) is the main policy making and representative organ of the UN. Decisions on important questions, such as those on peace and security, admission of new members and budgetary matters, require a two-thirds majority. Decisions on other questions are by simple majority. Each of the 193 member states of the United Nations has equal representation. The Assembly adopts its own rules of procedure and elects a President for each session."
unga-popup-text-agenda: "Mass surveillance gains ever increasing popularity among governments of various countries as a possible aid for fighting terrorism, preventing crime and resolving social unrest. Concurrently, it begets a certain vibe of mistrust between the administration and the citizens. More often than not, this practice ends up breaching the right to privacy of its subjects. With no standardized set of rules in place to overlook organizations exercising surveillance, there is a need for collective initiation to protect the rights of civilians. UNGA shall do precisely that by bringing together various countries to deliberate on the same in hope of homogenous and liberal laws."
ungaTopImage: "unga-top.jpg"

ecosoc-title: "The Economic and Social Council"
ecosoc-agenda-text: "Secession of the UK from the European Union: Trade, Border Policy, and Immigration"
about-ecosoc-text: "ECOSOC (United Nations Economic and Social Council), one of the six main organs of the United Nations established by the UN Charter..."
ecosoc-popup-text-about: "The working of the Economic and Social Council includes coordination of fourteen UN specialized agencies, ten functional commissions, and five regional commissions. Its purview extends over 70 percent of the human and financial resources of the entire UN system. The Council consists of 54 member states which are elected by the General Assembly for three-year terms. The Council holds a four-week substantive session each July, alternating between New York and Geneva. "
ecosoc-popup-text-agenda: "Secession of the UK from the EU is in a crisis. With around four months left to negotiate, both the parties involved must hasten dialogue lest they should end up without a deal. The Westminster Parliament persists in its indecision. Peace in Northern Ireland, sovereignty of Scotland, and livelihoods of millions of people are some of the many things that are being put at stake by this secession. With the prospect of a social conflict and international trade being in jeopardy, ECOSOC shall convene to make this transition as harmonious as possible."
ecosocTopImage: "ecosoc-top.jpg"

wto-title: "COMMITTEE X"
wto-agenda-text: "ADDRESSING POWER DISPARITY IN THE WTO: STRUCTURAL REFORM AND POLICY REVISIONS"
about-wto-text: "ECOSOC (United Nations Economic and Social Council), one of the six main organs of the United Nations established by the UN Charter..."
wto-popup-text-agenda: "The featured council of Edition X, this is the stage for the bigs. Introduced with this edition, the featured committee rakes in the brass of substantial debate in and around the circuit and pits them up against one another to heave it out in the most politically technical, lobbying intensive and inherently exciting debate. Such a committe wouldn't just be for one to participate in, it is worth spectating. Therefore developments in the council shall be streamed to the public and updates given to the other councils, while in action. Committee X calls for the most confident of orators and negotiators. Hence, the decoupled application procedure. Please note, only applicants with due experience in debate (primarily in UN simulations, secondarily elsewhere) shall be considered."
wto-popup-text-agenda2: "Trade is significant in the evolution of the humanity as a medium for exchange of not only commodities but also ideas. With the onset of modern era the scale of trade has experienced a drastic leap in terms of volumes. Moreover the need of regulations in the trade market in order to keep the playing field suitable for all has never been this high. With this objective WTO was established back in 1995 and with time it became integral part of world trade regulating nearly all of the worlds trade. But now it faces challenges that jeopardizes the very existence of the WTO and there is immediate need to bring reforms that constructively counter balances this menace."
wtoTopImage: "ecosoc-top.jpg"


locationLink: "https://www.google.co.in/maps/place/IIT+Guwahati+Conference+Hall/@26.1920316,91.6878585,17z/data=!4m5!3m4!1s0x375a5ac17d2b58d7:0xb853cd7b55039193!8m2!3d26.191117!4d91.692547?hl=en"
teamImage: "team.jpg"
signatureImage: "signature.png"
mun-image: "MUN.jpg"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "International Press"
  price: "1200"
  priceCurrency: "INR"
  ticketsNumber: "150"
  buyButtonLink: "http://iitgmun.org/apply/"
  buyButtonText: "Apply Now"
 -
  name: "Group Discount"
  price: "10% Off"
  priceCurrency: ""
  ticketsNumber: "50"
  featured: true
  buyButtonLink: "http://iitgmun.org/apply/"
  buyButtonText: "Apply Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["For groups of 5 or more"]
 -
  name: "Delegate"
  price: "1700"
  priceCurrency: "INR"
  ticketsNumber: "100"
  buyButtonLink: "http://iitgmun.org/apply/"
  buyButtonText: "Apply Now"


# Tweets Feed Block
tweetsFeedTitle2: "\"That the powerful play goes on, and you may contribute a verse."
tweetsFeedTitle3: "What will be your verse?\""
twitterHashTag2: "IITGMUN18"
deadPoets: "Dead Poets society"
waltWhitman: "O me! O life!, Walt Whitman"


# Workshop page
workshopPageLink: "/apply/"
